### ISSUE TITLE
Setup Kanbanboard

### ISSUE THREAD

**Issue by ybadr99** [ybadr99/Ruby_Capstone#9]
- project link: https://github.com/ybadr99/Ruby_Capstone/projects/1
you are 3 member
- team member1   : Kel-nana
- team member2   :Enning94
- team member      : ybadr99

**Comment by addod19** [comment]
## Hi @ybadr99, @Enning94 and @Kel-nana, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Link to the Kanban board provided :100: 
- [ ] Information about the number of people present :fireworks: 
- [ ] All columns in the board provided :rocket: 
- [ ] Task has desctiption and points assigned :100: 
- [ ] All tasks are assigned to students :rocket: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
